#  <font size = 10>What is Python Module?
<font size = 5> A module is a simple python file that contains collections of function,classes,and variables and has a.py extendion file.eg-math , os, datatime. 
    
                               You can use modules in your program by importing them.

In [ ]:
import math  # importing a module

In [ ]:
dir(math)   # checking all the variables,function,classes etc in the module

In [ ]:
math.sqrt(9)

In [ ]:
math.pi

In [1]:
from math import sqrt,pi,ulp,tau
sqrt(12)
pi
ulp(2)

4.440892098500626e-16

In [2]:
import custom_module                             

In [3]:
dir(custom_module)

['Employee',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'display',
 'x']

In [4]:
custom_module.x

[1, 2, 3, 4, 5]

In [5]:
x = custom_module.Employee("rohit",28)
x.show()

rohit 28


In [6]:
custom_module.display()

good morning


In [7]:
from custom_module import *
x

[1, 2, 3, 4, 5]

In [ ]:
display()

In [8]:
x = Employee("mohit",24)
x.show()

mohit 24


# <font size = 7 >What is Python Library?

<font size = 5 > Python library is a group of interconnected modules.It contain code bundles that can be reused in different programs.

# <font size = 7 > Python Libraries.

<font size = 5 >Various Python libraries makes programming easier.

<font size = 5 ><br>Some commonly used libraries are:
<font size = 4 ><br>1- NumPy
<font size = 4 ><br>2- Pandas
<font size = 4 ><br>3- SciPy
<font size = 4 ><br>4- Matplotlib 
<font size = 4 ><br>5- Scikit-learn

In [ ]:
import numpy,pandas,scipy, matplotlib  #  scikit-learn

In [ ]:
dir(numpy)

In [ ]:
dir(pandas)

In [ ]:
dir(scipy)

In [ ]:
dir(matplotlib)

# <font size = 6> Benefits of Python Librarues

- <font size = 3>Easy to learn
- <font size = 3>Open source
- <font size = 3>Efficient and muli-platform support
- <font size = 3>Huge collection of function,and modules
- <font size = 3>Big open- source community
- <font size = 3>Integrates well with enterprise
- <font size = 3>Apps and systems

# <font size = 6> Python Libraries

<font size = 3>1- ***NumPy*** - NumpPy is a library used for mathematics computations with multi-dimensional numerical data.
<font size = 3><br>2- ***pandas*** - pandas consist of a variety of analysis tools and configurable high- level data structures.
<font size = 3><br>3- ***Scipy*** - scientific python is on open-source high- level scientific computation package .This library is based on a NumPy extension.
<font size = 3><br>4- ***Matplotlib*** - It is also an open- source library that plots high- definition
<br>figures such as pie charts,histograms etc.
<font size = 3><br>5- ***Scikit-learn*** - The library containds a lot of ellicient  tooks for machine learning and ststisticl       modeling including classification ,regression,clustering and dimensionality reduction.

#  <font size= 6>Introduction to NumPy   ( Numaric Python)

- <font size= 4> It is Python library used for working with arrays.
- <font size= 4> It consists of a multidimensional array of objects and a collection of functions for manipulating them.
- <font size= 4> It conducts mathmatical and logical operations on arrays.

# <font size = 6>What  is an array?

- <font size = 3> An array is a central data structure of the NumPy library.<br>
- <font size = 3> It is an grid of homogeneous values(same data type).<br>
- <font size = 3> The ***rank*** of the array is the number of dimensions.<br>
- <font size = 3> The array object in NumPy is calles ***ndarray***.

# Advantages of NumPy
The following are the advantages of NumPy

- It provides an array object that is faster than traditional Python list.
- It provides supporting function.
- Array are frequently used in data science.

In [2]:
# Importing numpy

import numpy as np
arr = np.array([1,2,3,4,5])               # Creating an ndarray list
print(arr) 
arr

[1 2 3 4 5]


array([1, 2, 3, 4, 5])

In [3]:
arr = np.array({1,2,3,4,5})                 # Creating an ndarray set
print(arr)
arr

{1, 2, 3, 4, 5}


array({1, 2, 3, 4, 5}, dtype=object)

In [4]:
print(type(arr))

<class 'numpy.ndarray'>


In [6]:
arr = np.array({1 :"2",3 :'4'})                 # Creating an ndarray of dict
print(arr)
arr

{1: '2', 3: '4'}


array({1: '2', 3: '4'}, dtype=object)

In [7]:
arr = np.array((1,2,3,4,5))                 # Creating an ndarray tuple  ouput  
print(arr)
arr

[1 2 3 4 5]


array([1, 2, 3, 4, 5])

In [10]:
arr = np.array([1,"rohit",2,"rishi",3,4,5])                 # Creating an ndarray
print(arr)
print(type(arr))
arr

['1' 'rohit' '2' 'rishi' '3' '4' '5']
<class 'numpy.ndarray'>


array(['1', 'rohit', '2', 'rishi', '3', '4', '5'], dtype='<U11')

In [11]:
arr = np.array([1,"rohit",2,"rishi",3,4,None])                 # Creating an ndarray
print(arr)
print(type(arr))
arr

[1 'rohit' 2 'rishi' 3 4 None]
<class 'numpy.ndarray'>


array([1, 'rohit', 2, 'rishi', 3, 4, None], dtype=object)

In [12]:
arr = np.array([True,False,True])                 # Creating an ndarray
print(arr)
print(type(arr))
arr

[ True False  True]
<class 'numpy.ndarray'>


array([ True, False,  True])

In [18]:
arr = np.array([True,False,"str",123, "strn",True])                 # Creating an ndarray
print(arr)
print(type(arr))
arr

['True' 'False' 'str' '123' 'strn' 'True']
<class 'numpy.ndarray'>


array(['True', 'False', 'str', '123', 'strn', 'True'], dtype='<U11')

In [17]:
arr = np.array([True,False,123,23,True])                 # Creating an ndarray
print(arr)
print(type(arr))
arr

[  1   0 123  23   1]
<class 'numpy.ndarray'>


array([  1,   0, 123,  23,   1])

In [3]:
# Creating a Zero dimensinal array
import numpy as np
arr = np.array("60")
print(arr)

60


In [4]:
import numpy as np
arr = np.array(40)
print(arr)

40


In [5]:
# Creating a one-dimensinal array
# Each calue in a 1D array is 0D array

import numpy as np
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [7]:
# Creating a two-dimensinal array
# Each calue in a 1D arrays as its elements.

import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [2]:
# Creating a three-dimensinal array


import numpy as np
arr = np.array([([[1,2,3,4],[5,6,7,8]]),
                ([[1,2,3,4],[5,6,7,5]])])
print(arr)
arr.ndim 

[[[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 5]]]


3

In [3]:
# Creating a four-dimensinal array
import numpy as np
arr = np.array([[([[1,2,3,4],[5,6,7,8]]),
                 ([[1,2,3,4],[5,6,7,5]]),
                 ([[1,2,3,4],[5,6,7,8]]),
                 ([[1,2,3,4],[5,6,7,5]])]])
print(arr)
arr.ndim 

[[[[1 2 3 4]
   [5 6 7 8]]

  [[1 2 3 4]
   [5 6 7 5]]

  [[1 2 3 4]
   [5 6 7 8]]

  [[1 2 3 4]
   [5 6 7 5]]]]


4

In [10]:
print(np.array([[[[1,2],[3,5]],[[5,6],[6,7]],[[1,2],[3,5]],[[5,6],[6,7]]]]))
arr.ndim 

[[[[1 2]
   [3 5]]

  [[5 6]
   [6 7]]

  [[1 2]
   [3 5]]

  [[5 6]
   [6 7]]]]


4

In [46]:
# What could be another way to create an array
y = [1,2,3,4]
x = np.array(y)
print(x)
x

[1 2 3 4]


array([1, 2, 3, 4])

In [50]:
y = [[[1,2,3,4],[5,6,7,8]],[[6,6,7,5],[1,2,3,4]]]
x = np.array(y)
print(x)
x

[[[1 2 3 4]
  [5 6 7 8]]

 [[6 6 7 5]
  [1 2 3 4]]]


array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[6, 6, 7, 5],
        [1, 2, 3, 4]]])

In [52]:
x.ndim  # to check the dimensinal of arrays

3

In [ ]:
import

In [59]:
my_arr = np.array(range(10))
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
my_arr = np.arange(10)
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
my_arr = np.arange(100000)
my_arr

array([    0,     1,     2, ..., 99997, 99998, 99999])

In [11]:
my_arr = np.arange(100000)
my_list = list(range(100000))


In [12]:
%timeit my_arr2 = my_arr * 2

68.3 µs ± 1.76 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


# Data Types.

- The bit is the most basic unit of information in computing.
- The byte is a unit of information which contains 8 bits.


- bit = 1
- byte = 1 1 0 0 1 0 1 1

# Three types of data

- ***Byte string*** are constrained by the character encoding used . In character encodings like ASCII, each character is represented by a single byte,limiting the available characters to the 128 ASCII characters.

- ***Unicode strings*** cover a much larger range of characters,including those from various languages and special simbols.

- "***object***" data type is used from all other data types.

# Byte String    0,128 
- bytes
- bytes_
- S
- a

# Unicode String    

- U
- str
- str_
- unicode

# object
- object
- O

In [17]:
arr = np.array([True,False,"str",123,23,5.0,5j,True])                 
print(arr)
print(type(arr))
arr

['True' 'False' 'str' '123' '23' '5.0' '5j' 'True']
<class 'numpy.ndarray'>


array(['True', 'False', 'str', '123', '23', '5.0', '5j', 'True'],
      dtype='<U64')

In [24]:
arr = np.array([1.0,4j,True])
arr

array([1.+0.j, 0.+4.j, 1.+0.j])

# data type in numPy

In [2]:
import numpy as np

x = np.array([1,2,3,4],dtype = "object")
x,x.dtype

(array([1, 2, 3, 4], dtype=object), dtype('O'))

In [4]:
x = np.array(["string",1,2,3,"rohit"],dtype = "U")
x

array(['string', '1', '2', '3', 'rohit'], dtype='<U6')

In [6]:
x = np.array([2.3,True,False,"rohit"],dtype = "S")
x

array([b'2.3', b'True', b'False', b'rohit'], dtype='|S5')

In [7]:
x = np.array([2.3,True,False,"rohit"],dtype = "U")
x

array(['2.3', 'True', 'False', 'rohit'], dtype='<U5')

In [12]:
x = np.array([1,2,3,"rohit",-67],dtype = "object")
x

array(['1', '2', '3', 'rohit', '-67'], dtype='<U5')

In [14]:
x = np.array([1,2,3,4,-78],dtype = "uint")
x

array([         1,          2,          3,          4, 4294967218],
      dtype=uint32)

In [30]:
x = np.array([1,2,3,4,5,333333333333333333333333333,-76],dtype = "int32")
x,x.dtype

OverflowError: Python int too large to convert to C long

In [29]:
x = np.array(["hello rohit","rohittt","rohit"],dtype = "U")
x,x.dtype
# dtype('<U11') telling max num of string in this array



(array(['hello rohit', 'rohittt', 'rohit'], dtype='<U11'), dtype('<U11'))

In [34]:
x = np.array(["rohittt","rohit"],dtype = "S")
x,x.dtype

(array([b'rohittt', b'rohit'], dtype='|S7'), dtype('S7'))

In [33]:
len("rohittt")

7

# NumPy Array Inpection

In [11]:
import numpy as np

In [12]:
# ndarray ,ndim. - Returns the no of dimesnions

x = np.array([1,2,3])
x.ndim

1

In [13]:
x

array([1, 2, 3])

In [14]:
# ndarray.shape  - Return the shape
x.shape

(3,)

In [12]:
x = np.array([[1,2,3],[1,2,3]])
x.ndim

2

In [16]:
x

array([[1, 2, 3],
       [1, 2, 3]])

In [17]:
x.shape

(2, 3)

In [18]:
x = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
x.ndim

3

In [19]:
x

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [46]:
x.shape

(1, 3, 3)

In [87]:
x = np.array([[[[1,2,3,4],[4,5,6,5],[7,8,9,6],[3,4,5,7]]]])
x.ndim

4

In [88]:
x

array([[[[1, 2, 3, 4],
         [4, 5, 6, 5],
         [7, 8, 9, 6],
         [3, 4, 5, 7]]]])

In [89]:
x.shape  # 1 is 3D array,1 is 2D array,4 is 1D array,4 is 0D array 

(1, 1, 4, 4)

In [6]:
x = np.array(([[[[1,2,3,2],[1,2,3,5]]],[[[1,2,3,8],[4,5,6,6]]],[[[1,2,3,5],[4,5,6,3]]]]))
x.ndim

4

In [7]:
x

array([[[[1, 2, 3, 2],
         [1, 2, 3, 5]]],


       [[[1, 2, 3, 8],
         [4, 5, 6, 6]]],


       [[[1, 2, 3, 5],
         [4, 5, 6, 3]]]])

In [152]:
x.shape

(3, 1, 2, 4)

In [4]:
x = np.array([[[[2,3,4,6]],[[4,2,5,6]]],[[[1,2,2,4]],
            [[4,2,3,4]]],[[[1,2,3,4]],[[1,2,3,4]]]])

x.ndim

4

In [5]:
x

array([[[[2, 3, 4, 6]],

        [[4, 2, 5, 6]]],


       [[[1, 2, 2, 4]],

        [[4, 2, 3, 4]]],


       [[[1, 2, 3, 4]],

        [[1, 2, 3, 4]]]])

In [70]:
x.shape # 3 is telling 3D array,2 ia telling 2D array,1 is telling 1D array,4 is telling 0D array.
x.ndim

(3, 2, 1, 4)

In [64]:
x = np.array([[[[1,2,3,4]],[[1,2,3,4]]]])
x.ndim

4

In [66]:
x

array([[[[1, 2, 3, 4]],

        [[1, 2, 3, 4]]]])

In [65]:
x.shape  # 1 is telling 3D array,2 ia telling 2D array,1 is telling 1D array,4 is telling 0D array.

(1, 2, 1, 4)

In [30]:
x = np.array([[[1,2,3,2,7],[1,2,3,5,6],[2,3,4,5,5]],[[1,2,3,4,5],[1,2,3,8,5],[4,5,6,6,5]]])
x.ndim

3

In [31]:
x

array([[[1, 2, 3, 2, 7],
        [1, 2, 3, 5, 6],
        [2, 3, 4, 5, 5]],

       [[1, 2, 3, 4, 5],
        [1, 2, 3, 8, 5],
        [4, 5, 6, 6, 5]]])

In [32]:
x.shape

(2, 3, 5)

In [42]:
x = np.array([[[[1,2,3,2,7],[1,2,3,5,6],[2,3,4,5,5]],[[1,2,3,4,5],[1,2,3,8,5],[4,5,6,6,5]]]])
x.ndim


4

In [44]:
x

array([[[[1, 2, 3, 2, 7],
         [1, 2, 3, 5, 6],
         [2, 3, 4, 5, 5]],

        [[1, 2, 3, 4, 5],
         [1, 2, 3, 8, 5],
         [4, 5, 6, 6, 5]]]])

In [43]:
x.shape

(1, 2, 3, 5)

# CHANGE SHAPE

In [4]:
import numpy as np   
x = np.array([1,2,3,4])
print(x.shape)
print(x)
# (2,2)---2*2=4
# (2,3)---2*3=6
x.shape = (1,2,2)

(4,)
[1 2 3 4]


In [12]:
x = np.array([[1,2,3],[4,5,6]])
print(x.shape)

x.shape  = (3,2)
x.shape = (1,1,3,2)
x

(2, 3)


array([[[[1, 2],
         [3, 4],
         [5, 6]]]])

In [31]:
x = np.array([1,2,3,4,5,6,7,8])
print(x.shape)
x.shape = (2,4) # 2D
print(x)
x.shape = (1,2,4) # 3D
print(x)
x.shape = (1,1,2,4) # 4D
print(x)
x.shape = (1,2,1,2,2) # 5D
print(x)
x.shape = (2,1,1,2,1,2) # 6D
print(x)
x.shape = (1,2,1,1,1,2,2) # 7D
x

(8,)
[[1 2 3 4]
 [5 6 7 8]]
[[[1 2 3 4]
  [5 6 7 8]]]
[[[[1 2 3 4]
   [5 6 7 8]]]]
[[[[[1 2]
    [3 4]]]


  [[[5 6]
    [7 8]]]]]
[[[[[[1 2]]

    [[3 4]]]]]




 [[[[[5 6]]

    [[7 8]]]]]]


array([[[[[[[1, 2],
            [3, 4]]]]],




        [[[[[5, 6],
            [7, 8]]]]]]])

In [2]:
import numpy as np  
# nparray.size  - Return the no of elements.
x = np.array([1,2,3,4,5])
x.size

5

In [6]:
# nparray.dtype  - Returns the data type of the elements in the ndarray.
x.dtype

dtype('int32')

# Methods an functions used with ndarray

In [7]:
#np.ones(shape,dtype)  - Return a new array of given shape and type, filled with ones 
np.ones((2,3,4))  #.dtype

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [17]:
np.ones((1,5),dtype = "int32")


array([[1, 1, 1, 1, 1]])

In [22]:
np.ones((2,3,4)).dtype

dtype('float64')

In [21]:
np.ones((1,5),dtype = "U")

array([['1', '1', '1', '1', '1']], dtype='<U1')

In [20]:
x = np.ones((1,5),dtype = "int32").dtype
print(x)
type(x)   # x is an numpy.dtype is an object

int32


numpy.dtype[int32]

In [73]:
# np.zeros(shape,dtype) - Return a new array of given shape and type,filled with zeros.
np.zeros((1,3,2,4))

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [35]:
np.zeros((1,5),dtype = "int8")

array([[0, 0, 0, 0, 0]], dtype=int8)

In [28]:
# np.empty(shape,dtype) - Return a new array of given shape and type, without initializing entries.
np.empty((2,1),dtype ="U")

array([[''],
       ['']], dtype='<U1')

In [3]:
np.empty((2,4),"int8")

array([[   0,    0, -128,   63],
       [   0,    0, -128,   63]], dtype=int8)

In [26]:
# no.full(shape,dtype)- Return a new array of given shape and type,filled with fill_value.
np.full((2,3,4),90) # .dtype 

array([[[90, 90, 90, 90],
        [90, 90, 90, 90],
        [90, 90, 90, 90]],

       [[90, 90, 90, 90],
        [90, 90, 90, 90],
        [90, 90, 90, 90]]])

In [36]:
np.full((1,2,3),"o-o")

array([[['o-o', 'o-o', 'o-o'],
        ['o-o', 'o-o', 'o-o']]], dtype='<U3')

In [31]:
np.full((2,2,2),"rohit").size

8

In [81]:
np.full((2,1,2),True).dtype

dtype('bool')

In [76]:
# .dtype,.shape,.size,.ndim methods

In [33]:
np.array([1,2]).dtype

dtype('int32')

# Arange

In [8]:
# np.arange (start,stop,step,dtype) - return evenly spaced values within a given interval.
np.arange(3,10,2)

array([3, 5, 7, 9])

In [44]:
#we can use floating points start,stop,&step.
np.arange(2.5,10.5,2.5)

array([ 2.5,  5. ,  7.5, 10. ])

In [40]:
np.arange(2,10,1,dtype = "float") #dtype is not an defalt arguement its keyword.

array([2., 3., 4., 5., 6., 7., 8., 9.])

# linspace

In [55]:
# numpy.linspace (start,stop,num=50,endpoint=True,dtype)
# Return evenly spaced numbers over a specified interval.
# What do num=50 and endpoint=true suggest here?
# num=50 is the default value of num when not given,i.e. ,it will give 50 numbers in the range
# endpoint=true is the default value odf endpoint which tells us that the stop value is inclusive by default.
np.linspace(2,10,5,endpoint=False)

array([2. , 3.6, 5.2, 6.8, 8.4])

In [48]:
np.linspace(1,5,endpoint = False )

array([1.  , 1.08, 1.16, 1.24, 1.32, 1.4 , 1.48, 1.56, 1.64, 1.72, 1.8 ,
       1.88, 1.96, 2.04, 2.12, 2.2 , 2.28, 2.36, 2.44, 2.52, 2.6 , 2.68,
       2.76, 2.84, 2.92, 3.  , 3.08, 3.16, 3.24, 3.32, 3.4 , 3.48, 3.56,
       3.64, 3.72, 3.8 , 3.88, 3.96, 4.04, 4.12, 4.2 , 4.28, 4.36, 4.44,
       4.52, 4.6 , 4.68, 4.76, 4.84, 4.92])

In [4]:
np.array([np.array(1,2),(3,2)])

TypeError: Cannot interpret '2' as a data type

# Shape Manipulation in numpy.

In [1]:
import numpy as np

#.reshape()
x = np.array([1,2,3,4])
print(x.shape)
x = x.reshape(2,2)  # creates a copy of the ndarray.
print(x)

(4,)
[[1 2]
 [3 4]]


In [7]:
x

array([[1, 2],
       [3, 4]])

In [8]:
x.reshape(1,1,2,2,1) # we have to assine the reshape to change the x array

array([[[[[1],
          [2]],

         [[3],
          [4]]]]])

In [9]:
print(x)

[[1 2]
 [3 4]]


In [10]:
#.flatten()
x.flatten()     # flatter will change the multy D array into  1D array

array([1, 2, 3, 4])

In [11]:
#.ravel()     # ravel will make the array 1D array
x.ravel()

array([1, 2, 3, 4])

In [13]:
#.resize()  ------ just like .reshape
# The differnce between ,reshape and resize is reshape is note changing the x.array bt resize is change the shape of x .
x.resize(4,1)
x

array([[1],
       [2],
       [3],
       [4]])

In [21]:
print(x.reshape(2,2))

print(x)

[[1 2]
 [3 4]]
[[1]
 [2]
 [3]
 [4]]


# Concatination

Join a squence of array along an exixting axis.

In [3]:
# 2D array

x = np.array([[1,2,3],
              [4,5,6]])
y = np.array([[7,8,9],
             [10,12,13]])
print(f"x : \n {x} \ny : \n {y} \n")
print("Resulting array : \n" ,np.concatenate((x,y),axis=0)) # row- wise concatenation


x : 
 [[1 2 3]
 [4 5 6]] 
y : 
 [[ 7  8  9]
 [10 12 13]] 

Resulting array : 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 12 13]]


In [5]:
print(f"x : \n {x} \ny : \n {y} \n")
print("Resulting array : \n" ,np.concatenate((x,y),axis=1)) # column - wise concatenation


x : 
 [[1 2 3]
 [4 5 6]] 
y : 
 [[ 7  8  9]
 [10 12 13]] 

Resulting array : 
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 12 13]]


In [9]:
# 1D array
n1 = np.array([1,2,3,4])
n2 = np.array([5,6,7,8])
print(f"n1 : \n {n1} \n n2 : {n2} \n")
print("for axis = 0 \n",np.concatenate((n1,n2),axis = 0),"\n")

n1 : 
 [1 2 3 4] 
 n2 : [5 6 7 8] 

for axis = 0 
 [1 2 3 4 5 6 7 8]


In [10]:
print(f"n1 : \n {n1} \n n2 : {n2} \n")
print("for axis = 0 \n",np.concatenate((n1,n2),axis = 1))

n1 : 
 [1 2 3 4] 
 n2 : [5 6 7 8] 



AxisError: axis 1 is out of bounds for array of dimension 1

# Hstack and Vstack.


In [15]:
# 2D array
x = np.array([[1,2,3],
             [4,5,6]])
y = np.array([[7,8,9],
             [10,11,12]])
np.hstack((x,y))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [17]:
np.vstack((x,y))    ## np.concatenate((x,y),axis=1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [19]:
# 1D array
n1 = np.array([1,2,3,4])
n2 = np.array([5,6,7,8])
np.vstack((n1,n2))    # np.concatenate((x,y),axis=0)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
np.hstack((n1,n2))   # np.concatenate((x,y),axis=0)

array([1, 2, 3, 4, 5, 6, 7, 8])

# Indexing ,Slicing & Striding

In [66]:
# 1D  
# (Axis 0,)
# (column,)
# (0D)
x = np.array([1,2,3,4])
print(x[3])
print(x[2])

4
3


In [29]:
x = np.array([[1,2,3,4,5],
             [6,7,8,9,10]])
print(x[0,1])  # preferred way
x[1][4]

2


10

In [23]:
# 1D  
# (Axis 0 , Axis 1)
# (Row , Column,)
# (1D , 0D)
x = np.array ([[1,2,3,4],
              [5,6,7,8]])
x[0,2]  # preferred way

3

In [24]:
x[0][3]   # altrnative way

4

In [25]:
x = np.array ([[1,2,3,4],
              [5,6,7,8]])
x[-2,0]  # preferred way

1

In [68]:
# indexing in 3D array
# (axis 0, axis 1,axis 2)
# (2D,1D,0D)
import numpy as np
x = np.array([[[1,2,3,4],
              [5,6,7,8]],
              [[2,3,4,5],
             [7,8,9,9]]])
print(x[1])
print(x[0])
            
x[1:0,1]

[[2 3 4 5]
 [7 8 9 9]]
[[1 2 3 4]
 [5 6 7 8]]


array([], shape=(0, 4), dtype=int32)

In [34]:
x = np.array([[[1,2,3,4],
              [5,6,7,8]],
              [[2,3,4,5],
             [7,8,9,9]]])
x[0:1]

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]]])

In [63]:
x[1,0,2]

4

In [39]:
x[1:2]

array([[[2, 3, 4, 5],
        [7, 8, 9, 9]]])

In [55]:
x[1:3,1,3]

array([9])

# Slicing &Striding

Starts(inclusive):Stop(exclusive):Step

In [69]:
# 1D
x = np.array([1,2,3,4])
x[0:4:2]

array([1, 3])

In [70]:
x[::2]

array([1, 3])

In [72]:
x[1::1]

array([2, 3, 4])

In [73]:
# Slicing in 2D
import numpy as np
a= np.array([[1,2,3],[4,5,6]])
a[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [74]:
a[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [76]:
a[0:2,0]

array([1, 4])

In [78]:
a[0,1:3]

array([2, 3])

# Arithmetic with Numpy
- Any operation between equal-size arrays happens element-wise. 

In [79]:
import numpy as np
a = np.array([[1,2,3],
            [4,5,6]])
b = np.array([[2,3,4],
             [5,6,7]])
a+b

array([[ 3,  5,  7],
       [ 9, 11, 13]])

In [80]:
a*b

array([[ 2,  6, 12],
       [20, 30, 42]])

In [81]:
a//b

array([[0, 0, 0],
       [0, 0, 0]])

In [82]:
a%b

array([[1, 2, 3],
       [4, 5, 6]])

In [83]:
a**b

array([[     1,      8,     81],
       [  1024,  15625, 279936]])

# Arithmetic operations with scalars propagate the scalar argument to each element in the array.
- Operations between differently sized arrays is called bordcasting.

In [84]:
import numpy as np
a = np.array([[1,2,3],
            [4,5,6]])
b = np.array([[2,3,4],
             [5,6,7]])
a*2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [85]:
a-2

array([[-1,  0,  1],
       [ 2,  3,  4]])

In [86]:
b*2

array([[ 4,  6,  8],
       [10, 12, 14]])

In [89]:
a-np.array([3])

array([[-2, -1,  0],
       [ 1,  2,  3]])

In [90]:
a+2+3+4

array([[10, 11, 12],
       [13, 14, 15]])

# Universal Functions
- A universal function that perfrom element-wise operations on data in ndarrays.

In [91]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
np.add(a,b)   # or a+b

array([ 6,  8, 10, 12])

In [92]:
np.subtract(b,a)

array([4, 4, 4, 4])

In [94]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [95]:
import numpy

In [96]:
dir (numpy)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__packag

# Pseudo-Random Number Generation

In [2]:
# In python we have a built-in module random
import random
random.random()

0.6160404787728565

In [3]:
random.seed(2)    # same seed value will generate the same ramdom no. it will not change.
random.random() 

0.9560342718892494

In [5]:
import numpy as np
np.random.seed(1)
np.random.random()

0.417022004702574

# Bollean Array

In [7]:
import numpy as np
name = np.array(["rohit","gaurav","mohit","himanshu","rohit"])


In [10]:
name =="rohit"

array([ True, False, False, False,  True])

In [9]:
name[name=="rohit"]

array(['rohit', 'rohit'], dtype='<U8')

In [11]:
name[name=="rohit"] # index num is not presurv

array(['rohit', 'rohit'], dtype='<U8')

In [18]:
name[name=="rohit"][1]

'rohit'

In [15]:
name[1]

'gaurav'

In [16]:
ar1 = np.array([["hello","word"],["xyz"]])  # if the elenet will not be same it will becomw 1darray
print(ar1)
ar1.ndim

[list(['hello', 'word']) list(['xyz'])]


C:\Users\Rohit Kr\AppData\Local\Temp\ipykernel_12492\1106189503.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  ar1 = np.array([["hello","word"],["xyz"]])  # if the elenet will not be same it will becomw 1darray


1