In [2]:
import numpy as np

array = np.array([[1,2,3,4],[5,6,7,8]])  # columns
print(array)
a = array[0]
b = array[1]
c = array[0]
a = b
b = c
array = np.array([a,c])
array

[[1 2 3 4]
 [5 6 7 8]]


array([[5, 6, 7, 8],
       [1, 2, 3, 4]])

In [8]:
array = np.array([[1,2,3],[4,5,6]])   # columns
array[:,[0,1]]= array[:,[1,0]]
array

array([[2, 1, 3],
       [5, 4, 6]])

In [14]:
array = np.array([[1,2,3,4],[5,6,7,8]])   # rows
array[[1,0]] = array[[0,1]]
array

array([[5, 6, 7, 8],
       [1, 2, 3, 4]])

In [12]:
array = np.array([[1,2,3,4],[5,6,7,8]])  # reverse
r_array = array[:,::-1]
print(r_array)

[[4 3 2 1]
 [8 7 6 5]]


In [24]:
array = np.array([[1,2,3,4],[5,6,7,8]])
array[:,[0,1,2,3]]=array[:,[3,2,1,0]]
array

array([[4, 3, 2, 1],
       [8, 7, 6, 5]])

In [73]:
array = np.array([[1,3,5,6],[8,4,9,7]])
array[0] = array[0][::-1]
array[1] = array[1][::-1]
array


array([[6, 5, 3, 1],
       [7, 9, 4, 8]])

In [18]:
array = [1,2,3,4,5,6,7,8,9,10]    
start = int(input())
stop = int(input())
x = np.array([num for num in array if start <= num <= stop])     # list comprihencen
print(x)


3
7
[3 4 5 6 7]


In [17]:
y = np.array([1,3,5,7,8,5,9,8,6,5,5,9,10])
lst = []
for i in y:
    if 4<=i<=10:
        lst.append(i)
lst

[5, 7, 8, 5, 9, 8, 6, 5, 5, 9, 10]

In [3]:
y = np.array([1,2,3,4,5,6,7,8,9,10])
y[(y>=4) & (y<=10)]      # logical & operator




array([ 4,  5,  6,  7,  8,  9, 10])

In [4]:
(y>=4) & (y<=10)   # Boolean array

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [3]:
words = ["array","numpy"]
vob = ["a","e","i","o","u"]
lst =[]
for word in words:
    for wrd in word:
        for wd in vob:
            if wrd == wd:
                lst.append(word)
#print(lst)                
for word in lst:
    if lst.count(word)==1:
        lst.remove(word)
        print(set(lst))


{'array'}


In [12]:
words= ["array","numpy","once"]   # short 
vowel_words =[]
for x in words:
    count = 0
    for i in x:
        if i in "aeiouAEIOU":
            count+=1
    if count>=2:
        vowel_words.append(x)
vowel_words

['array', 'once']